# General settings
# setopt nobeep
# setopt correct

alias gcc="/opt/homebrew/Cellar/gcc/14.1.0_2/bin/gcc-14"
alias g++="/opt/homebrew/Cellar/gcc/14.1.0_2/bin/g++-14"

# Variables for Make
# export CC="gcc"
export CFLAGS=""

# Generic variables
export BROWSER=brave
export EDITOR=nvim
export VISUAL=nvim
export TERM=xterm-256color
# export TERM=alacritty
export TERMINAL=alacritty

DISABLE_AUTO_TITLE="true"
PROMPT='%B%F{blue}%~%f%F{cyan}%f%b '

# set window title to working directory
precmd() {
    eval 'echo -ne "\e]2;$(pwd)\e\\"'
}

# '%' if user has no elevated privileges,
# '#' if he does
# PROMPT='%F{blue}%~%f%F{cyan} %#%f '

zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit -i

# History
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
setopt autocd

# Don't consider certain characters part of a word
WORDCHARS=${WORDCHARS//\/[&.;]}

# Do not write a duplicate event to the history file.
# setopt HIST_SAVE_NO_DUPS
#
# setopt appendhistory
# setopt inc_append_history

# Aliases
alias ls='ls --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias gis='git status'
alias gic='git commit'
alias gd='git diff'
alias ga='git add'
alias gp='git push'
alias gdc='git diff --cached'
alias gds='git diff --stat'
alias gc='git checkout'
alias gcb='git checkout .'
alias gattach='git commit --amend --no-edit'

alias upgrade-pip3-packages='pip3 install $(pip3 list | tail -n +3 | tr -s " " | cut -d " " -f 1) --upgrade'

alias python='python3'

alias mp='multipass'


# Exports
# export PATH="$HOME/.scripts:/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.docker/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"
export BACKGROUND='/home/tom/Pictures/Wallpapers/city_pixelart.png'
export LTEX_GLOBAL_STORAGE_PATH="$XDG_CONFIG_HOME/nvim/ltex-settings"

export CPATH="/opt/homebrew/opt/libomp/include:/opt/homebrew/Cellar/boost/1.87.0/include:$CPATH"
export LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:/opt/homebrew/Cellar/boost/1.87.0/lib:$LIBRARY_PATH"
export LD_LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:/opt/homebrew/Cellar/boost/1.87.0/lib:$LD_LIBRARY_PATH"

export TORCH_PATH="/opt/homebrew/lib/python3.11/site-packages/torch/share/cmake"

fpath=(~/.config/zsh/plugins/zsh-completions/src $fpath)
fpath=(~/.config/zsh/plugins/zsh-syntax-highlighting/src $fpath)
fpath=(~/.config/zsh/plugins/zsh-autosuggestions/src $fpath)

# Source plugins
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/plugins/web-search/web_search.plugin.zsh

# Keybindings

# Use Ctrl-a to move cursor to the beginning of the line
bindkey '^A' beginning-of-line

# Use delete key like in bash
bindkey '^[[3~' delete-char

# Use Ctrl-ArrowKeys to navigate words
bindkey '^[0c' forward-word
bindkey '^[0d' backward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# Use Ctrl-Space to accept the suggestion
bindkey '^ ' autosuggest-accept

source ~/.exports

# FZF Catppuccin Frappé
# export FZF_DEFAULT_OPTS=" \
# --color=bg+:#414559,bg:#303446,spinner:#f2d5cf,hl:#e78284 \
# --color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf \
# --color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284"

# FZF Catppuccin Macchiato
# export FZF_DEFAULT_OPTS=" \
# --color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
# --color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
# --color=marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796"

# FZF Catppuccin Mocha
# export FZF_DEFAULT_OPTS=" \
# --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
# --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
# --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"

export DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/libomp/19.1.6/lib/:/opt/homebrew/lib/python3.11/site-packages/torch/lib/:$DYLD_LIBRARY_PATH

export FZF_DEFAULT_OPTS=""
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
