# General settings
setopt nobeep
setopt correct

# Variables for Make
export CC="gcc"
export CFLAGS="-ggdb3 -O0 -std=c11 -Wall -Werror"

# Generic variables
export BROWSER=brave
export EDITOR=nvim
export VISUAL=nvim
export TERM=alacritty
export TERMINAL=alacritty

# Comment the generic variables above and uncomment
# this if there are issues whith weird behavior
# export TERM=xterm


DISABLE_AUTO_TITLE="true"
PROMPT='%B%F{blue}%~%f%F{cyan}%f%b '

# set window title to working directory
precmd() {
    eval 'echo -ne "\e]2;$(pwd)\e\\"'
}

# '%' if user has no elevated privileges,
# '#' if he does
# PROMPT='%F{blue}%~%f%F{cyan} %#%f '

zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit

# History
HISTFILE=~/.config/zsh/histfile
HISTSIZE=10000
SAVEHIST=10000
setopt autocd

# Don't consider certain characters part of a word
WORDCHARS=${WORDCHARS//\/[&.;]}

# Do not write a duplicate event to the history file.
setopt HIST_SAVE_NO_DUPS

setopt appendhistory
setopt inc_append_history

# Aliases
alias ls='ls --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias gis='git status'
alias gic='git commit'
alias gd='git diff'
alias ga='git add'
alias gp='git push'
alias gdc='git diff --cached'
alias gds='git diff --stat'
alias gc='git checkout'
alias gcb='git checkout .'
alias gattach='git commit --amend --no-edit'

alias upgrade-pip3-packages='pip3 install $(pip3 list | tail +3 | tr -s " " | cut -d " " -f 1) --upgrade'

alias python='python3'


# Exports
export PATH="$HOME/.scripts:/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config/"
export BACKGROUND='/home/tom/Pictures/Wallpapers/city_pixelart.png'

fpath=(~/.config/zsh/plugins/zsh-completions/src $fpath)
fpath=(~/.config/zsh/plugins/zsh-syntax-highlighting/src $fpath)
fpath=(~/.config/zsh/plugins/zsh-autosuggestions/src $fpath)

# Source plugins
source ~/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
source ~/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Keybindings

# Use Ctrl-a to move cursor to the beginning of the line
bindkey '^A' beginning-of-line

# Use delete key like in bash
bindkey '^[[3~' delete-char

# Use Ctrl-ArrowKeys to navigate words
bindkey '^[0c' forward-word
bindkey '^[0d' backward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# Use Ctrl-Space to accept the suggestion
bindkey '^ ' autosuggest-accept

source ~/.exports
