#!/bin/bash

if [ $# -eq 1 ]; then
    name=$1
else

    dir="$(pwd | rev | cut -d/ -f1 | rev | sed -r  's/://g')"
    counter=0

    while read -r entry; do
        if [[ counter -eq 0 ]]; then
            if [[ ${dir} == ${entry} ]]; then
                counter=$((${counter} + 1))
            fi
        else
            if [[ "${dir}${counter}" == ${entry} ]]; then
                counter=$((${counter} + 1))
            fi
        fi
    done <<< "$(tmux ls | cut -d ':' -f1)"


    if [[ counter -ne 0 ]]; then
        dir="${dir}${counter}"
    fi

    name=${dir}
fi

tmux new-session -s "${name}"
